version: "3"

x-orb-slam3-common: &orb_slam3_common
    privileged: true
    network_mode: host
    ipc: host
    pid: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY
      - TERM
      - QT_X11_NO_MITSHM=1
    entrypoint: /bin/bash

services:
  orb_slam3_22_humble:
    <<: *orb_slam3_common
    image: orb-slam3-humble:22.04
    volumes:
      #full dev
      - /dev:/dev:rw
      #full media
      - /media:/media:rw
      #Time
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
      #ros-workspaces
      - ./container_root/:/root/
      - ./ros_env_vars.sh:/root/ros_env_vars.sh
      - ./orb_slam3_ros2_wrapper/:/root/colcon_ws/src/orb_slam3_ros2_wrapper/
      - ./orb_slam3_map_generator/:/root/colcon_ws/src/orb_slam3_map_generator/
      - ./slam_msgs/:/root/colcon_ws/src/slam_msgs/
      - ./ORB_SLAM3/:/home/orb/ORB_SLAM3/

  orb_slam3_22_humble_nvidia:
    <<: *orb_slam3_common
    image: orb-slam3-humble-nvidia:22.04
    volumes:
      #full dev
      - /dev:/dev:rw
      #full media
      - /media:/media:rw
      #Time
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
      #ros-workspaces
      - ./container_root/:/root/
      - ./ros_env_vars.sh:/root/ros_env_vars.sh
      - ./orb_slam3_ros2_wrapper/:/root/colcon_ws/src/orb_slam3_ros2_wrapper/
      - ./orb_slam3_map_generator/:/root/colcon_ws/src/orb_slam3_map_generator/
      - ./slam_msgs/:/root/colcon_ws/src/slam_msgs/
      - ./FastTrack/:/home/orb/ORB_SLAM3/
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
